# Generated by Django 3.2.22 on 2023-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
