# Generated by Django 3.2.22 on 2023-11-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_created_date_post_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_datetime',
        ),
    ]
