# Generated by Django 3.2.22 on 2023-11-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_create_date_post_created_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fk_company',
            new_name='company',
        ),
    ]
