# Generated by Django 3.2.22 on 2023-11-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_fk_company_post_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_datetime',
        ),
        migrations.AlterField(
            model_name='position',
            name='applicants_value',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.SmallIntegerField(null=True),
        ),
    ]
