# Generated by Django 3.2.22 on 2023-11-15 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20231115_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
