# Generated by Django 3.2.22 on 2023-11-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_created_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_post',
            new_name='upload_post_date',
        ),
    ]
