# Generated by Django 3.2.22 on 2023-11-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_upload_post_post_upload_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='register_id',
            field=models.IntegerField(max_length=40),
        ),
    ]
