# Generated by Django 3.2.22 on 2023-11-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='register_id',
            field=models.IntegerField(),
        ),
    ]
