# Generated by Django 3.2.22 on 2023-11-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_register_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_post_date',
            new_name='publish_date',
        ),
    ]
