# Generated by Django 3.2.22 on 2023-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_upload_post_date_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
