# Generated by Django 3.2.22 on 2023-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_position_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='salary',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='salary_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='salary_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='register_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
