# Generated by Django 3.2.22 on 2023-11-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20231115_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='post',
        ),
    ]
