# Generated by Django 3.2.22 on 2023-11-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.description'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.tags'),
        ),
    ]
