# Generated by Django 3.2.22 on 2023-11-15 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20231115_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.tags'),
        ),
    ]
