# Generated by Django 3.2.22 on 2023-11-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.PositiveSmallIntegerField(choices=[(1, 'Vilnius'), (2, 'Kaunas'), (3, 'Klaipėda'), (4, 'Šiauliai'), (5, 'Panevėžys')])),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
